/**
 * Versioned circuit declarations for `@zkpe/circuit-lib` (ADR-0007, ADR-0008).
 *
 * A {@link CircuitDefinition} is the static, source-of-truth description of a
 * circuit: its id, version, source file, public/private interface in manifest
 * terms, and artifact layout. Compiled artifacts live under
 * `build/<artifactBase>.*` and are regenerated by `scripts/build-circuits.mjs`;
 * their content hashes are certified into a `CircuitManifest` by
 * `scripts/certify-circuits.mjs`.
 */

import type { CircuitInputSpec, CircuitOutputSpec } from '@zkpe/proof-format';

/** Static description of a circuit shipped by this package. */
export interface CircuitDefinition {
  /** Stable identifier, e.g. `poseidon-preimage`. Immutable once registered. */
  readonly id: string;
  /** Semver circuit version; bump on any signal-graph change (G-Ver). */
  readonly version: string;
  /** Source file name under `circuits/`. */
  readonly file: string;
  /** Base name of built artifacts under `build/` (`<base>.r1cs`, `_js/<base>.wasm`, `<base>.zkey`). */
  readonly artifactBase: string;
  /** Public input schema, canonical order (matches the manifest). */
  readonly inputs: readonly CircuitInputSpec[];
  /** Private input schema. */
  readonly privateInputs: readonly CircuitInputSpec[];
  /** Output schema (currently `u1` flags and `field` values). */
  readonly outputs: readonly CircuitOutputSpec[];
  /** Constraint budget: `estimated` is measured at build time, `max` is a registry gate. */
  readonly constraints: { readonly estimated: number; readonly max: number };
}

/**
 * The v1 circuit set (ADR-0008): `poseidon-preimage@1` and `merkle-inclusion@1`.
 * Both use Poseidon as the only in-circuit hash (see `packages/engine` docs).
 */
export const CIRCUIT_DEFS: readonly CircuitDefinition[] = [
  {
    id: 'poseidon-preimage',
    version: '1.0.0',
    file: 'poseidon-preimage.circom',
    artifactBase: 'poseidon-preimage',
    inputs: [],
    privateInputs: [{ id: 'preimage', type: 'field', arity: 2 }],
    outputs: [{ id: 'digest', type: 'field', arity: 1 }],
    constraints: { estimated: 240, max: 65536 },
  },
  {
    id: 'merkle-inclusion',
    version: '1.0.0',
    file: 'merkle-inclusion.circom',
    artifactBase: 'merkle-inclusion',
    inputs: [{ id: 'root', type: 'field', arity: 1 }],
    privateInputs: [
      { id: 'leaf', type: 'field', arity: 1 },
      { id: 'siblings', type: 'field', arity: 4 },
      { id: 'pathBits', type: 'u1', arity: 4 },
    ],
    outputs: [
      { id: 'rootPub', type: 'field', arity: 1 },
      { id: 'isZero', type: 'u1', arity: 1 },
    ],
    constraints: { estimated: 974, max: 65536 },
  },
];

/** Look up a circuit by id; throws `RangeError` when unknown. */
export function getCircuitDefinition(id: string): CircuitDefinition {
  const def = CIRCUIT_DEFS.find((d) => d.id === id);
  if (!def) {
    throw new RangeError(`unknown circuit id: ${JSON.stringify(id)}`);
  }
  return def;
}

/** All registered circuit ids, in canonical order. */
export function listCircuitIds(): string[] {
  return CIRCUIT_DEFS.map((d) => d.id);
}
