name: OSV-Scanner

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '30 4 * * 1' # Run weekly on Monday at 04:30 UTC

permissions:
  contents: read

jobs:
  osv-scanner:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Run OSV-Scanner
        uses: google/osv-scanner-action/osv-scanner-action@19ec1116569a47416e11a45848722b1af31a857b # v1.9.0
        with:
          scan-args: |-
            --format=sarif
            --output=results.sarif
            --skip-git
            --recursive
            ./
        continue-on-error: true

      - name: Upload OSV-Scanner SARIF report
        uses: github/codeql-action/upload-sarif@ff2f1c621b7f889edc0d3c761ac2e6a3f8cdb0dd # v4
        with:
          sarif_file: results.sarif
          category: osv-scanner
